apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  serviceName: db
  selector:
    matchLabels:
      name: db
  replicas: 1
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
      - name: db
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysqlport
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nodeapp-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: nodeapp-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nodeapp-secret
              key: MYSQL_PASSWORD
        # - name: MYSQL_DATABASE
        #   valueFrom:
        #     secretKeyRef:
        #       name: nodeapp-secret
        #       key: database